# Generated by Django 5.2.16 on 2026-07-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_key', models.CharField(max_length=512, unique=True)),
                ('label', models.CharField(max_length=512)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=128)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.CharField(blank=True, default='', max_length=32)),
                ('price_per_gallon', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocode_status', models.CharField(db_index=True, default='pending', help_text='pending | ok | failed', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['opis_id'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='fuel_fuelst_latitud_e7de73_idx'), models.Index(fields=['state', 'is_active'], name='fuel_fuelst_state_7c924f_idx'), models.Index(fields=['is_active', 'price_per_gallon'], name='fuel_fuelst_is_acti_f6d5a8_idx')],
            },
        ),
    ]
